### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by user404d**
Update master with most recent schema.

`games.log_url` field needed to be lengthened as game log urls tend to be long (especially with long hostnames).

Submissions were added to track Team docker images and their build status.

Game_submissions are used to tie Games to Submissions for the purposes of playing a game. This allows for Games to have a Team's Submission (aka client) get tied to the outcome of a Game. This will help competitors better track how specific Submissions are performing.

### CODE REVIEW

**Comment by user404d** [comment]
I'll leave this for another hour or so before closing @renodubois @michael-beaver.

**Comment by russleyshaw** [comment]
This should be generated from the `colisee-lib/db` module to maintain compatability

**Comment by renodubois** [comment]
Looks good to me!

**Comment by michael-beaver** [comment]
Looks good to me too

**Pull request merged**
